//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int BookmarkID { get; set; }
        public Nullable<int> SeekerID { get; set; }
        public Nullable<int> JobID { get; set; }
    
        public virtual JobVacancy JobVacancy { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
