//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int MessageID { get; set; }
        public Nullable<int> ChatID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public string Sender { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
