//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDetail
    {
        public int EducationID { get; set; }
        public Nullable<int> SeekerID { get; set; }
        public string University { get; set; }
        public string Degree { get; set; }
        public string Major { get; set; }
        public Nullable<int> GraduationYear { get; set; }
        public Nullable<decimal> GPA { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
