//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobVacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobVacancy()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.JobApplications = new HashSet<JobApplication>();
            this.JobViews = new HashSet<JobView>();
        }
    
        public int VacancyID { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public string JobTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string EmploymentType { get; set; }
        public Nullable<System.DateTime> ApplicationDeadline { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual Category Category { get; set; }
        public virtual Employer Employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplication> JobApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobView> JobViews { get; set; }
    }
}
